[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
yare = "1.0.1"
comfy-table = "5.0.0"